import type { CategoryId } from '../types'

export const CATEGORY_KEYWORDS: Record<CategoryId, string[]> = {
  structure: [
    'lumber',
    'plywood',
    '2x4',
    '2x6',
    'osb',
    'stud',
    'framing',
    'sheet metal',
    'steel',
    'rust',
    'primer',
    'weld',
    'rivet',
    'screw',
    'bolt',
    'bracket',
    'angle iron',
    'joist',
    'deck',
    'pressure treat',
  ],
  insulation: [
    'insulation',
    'foam',
    'rigid foam',
    'polyiso',
    'rockwool',
    'mineral wool',
    'thinsulate',
    'reflectix',
    'spray foam',
    'vapor barrier',
    'housewrap',
    'fiberglass',
    'denim insul',
  ],
  electrical: [
    'wire',
    'wiring',
    'outlet',
    'breaker',
    'fuse',
    'electrical',
    'conduit',
    'romex',
    'switch',
    'junction',
    'led strip',
    'dimmer',
    'gauge wire',
    'terminal',
    'gfci',
    'receptacle',
    'nm-b',
    'thhn',
  ],
  solar: [
    'solar',
    'mppt',
    'inverter',
    'lithium',
    'lifepo',
    'battery',
    'deep cycle',
    'charge controller',
    'pv panel',
    'solar panel',
    'busbar',
    'anderson',
    'victron',
    'renogy',
  ],
  plumbing: [
    'pipe',
    'pvc',
    'pex',
    'plumbing',
    'valve',
    'faucet',
    'fitting',
    'water pump',
    'tank',
    'hose',
    'sharkbite',
    'drain',
    'elbow',
    'coupling',
  ],
  propane: [
    'propane',
    'heater',
    'furnace',
    'diesel heater',
    'mr heater',
    'regulator',
    'gas line',
    'stove',
    'oven',
  ],
  interior: [
    'drywall',
    'shiplap',
    'paneling',
    'trim',
    'molding',
    'caulk',
    'paint',
    'adhesive',
    'construction adhesive',
    'liquid nails',
  ],
  kitchen: [
    'sink',
    'countertop',
    'fridge',
    'refrigerator',
    'cooktop',
    'microwave',
    'cabinet',
    'kitchen',
    'dishwasher',
  ],
  bathroom: [
    'toilet',
    'shower',
    'bath',
    'bathroom',
    'cassette',
    'composting',
    'vanity',
    'mirror',
  ],
  flooring: ['floor', 'flooring', 'vinyl', 'lvp', 'laminate', 'subfloor', 'tile', 'carpet'],
  windows: ['window', 'door', 'awning', 'seal', 'weatherstrip', 'glass', 'egress'],
  furniture: ['mattress', 'sofa', 'couch', 'table', 'chair', 'bed', 'cushion', 'furniture'],
  tools: [
    'drill',
    'saw',
    'tool',
    'clamp',
    'tape measure',
    'screwdriver',
    'wrench',
    'bit set',
    'multimeter',
    'utility knife',
    'fuel filter',
    'oil filter',
    'air filter',
    'filter kit',
    'filter',
    'racor',
    'caterpillar',
    'powerstroke',
    'diesel',
    'adapter kit',
    'parfit',
  ],
  safety: [
    'extinguisher',
    'smoke',
    'co detector',
    'fire',
    'first aid',
    'safety',
    'harness',
    'goggle',
  ],
  fuel: [
    'fuel',
    'gasoline',
    'diesel',
    'gas station',
    'shell',
    'chevron',
    'exxon',
    'bp ',
    'mobil',
    'tow',
    'towing',
    'wrecker',
    'roadside',
    'recovery',
    'falzone',
  ],
  misc: [],
}

export const VENDOR_HINTS = [
  'home depot',
  'lowe',
  "lowe's",
  'lowes',
  'menards',
  'harbor freight',
  'ace hardware',
  'amazon',
  'walmart',
  'target',
  'costco',
  "sam's",
  'sams club',
  'tractor supply',
  'grainger',
  'autozone',
  'oreilly',
  "o'reilly",
  'napa',
  'ikea',
  'rei',
  'northern tool',
  'micro center',
  'best buy',
  'swag performance',
  'swagperformanceparts',
]

export function categorizeText(text: string): { categoryId: CategoryId; score: number } {
  const lower = text.toLowerCase()
  let best: CategoryId = 'misc'
  let bestScore = 0

  for (const [id, words] of Object.entries(CATEGORY_KEYWORDS) as [CategoryId, string[]][]) {
    if (id === 'misc') continue
    let score = 0
    for (const w of words) {
      if (lower.includes(w)) score += w.includes(' ') ? 3 : 2
    }
    if (score > bestScore) {
      bestScore = score
      best = id
    }
  }
  return { categoryId: best, score: bestScore }
}
